from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time
driver=webdriver.Chrome()
driver.implicitly_wait(10)
driver.get("https://www.selenium.dev/selenium/web/web-form.html")
textinput=driver.find_element(By.ID,"my-text-id")
textinput.send_keys("hemesh")
time.sleep(1)
password=driver.find_element(By.NAME,"my-password") 
password.send_keys("Hemesh@348667")
time.sleep(1)
textarea=driver.find_element(By.NAME,"my-textarea")
textarea.send_keys("fukweyvf ahvdkauvha dakvdakd")
time.sleep(1)
dropdown=driver.find_element(By.NAME,"my-select")
dropdownselect=Select(dropdown)
dropdownselect.select_by_value("3")
time.sleep(1)
print("dropdown selected")
datalist=driver.find_element(By.NAME,"my-datalist")
datalist.send_keys("Los Angeles")
print("datalist changed")
time.sleep(1)
checkbox=driver.find_element(By.ID,"my-check-2")
checkbox.click()
print("radio button clicked")
time.sleep(1)
radiobtn=driver.find_element(By.ID,"my-radio-1")
radiobtn.click()
print("radio button clicked")
time.sleep(1)
upload=driver.find_element(By.NAME,"my-file")
upload.send_keys("C:\\Users\\hemes\\OneDrive\\Pictures\\Screenshots\\Screenshot 2025-03-25 115943.png")
print("img uploaded")
time.sleep(1)
colorpicker=driver.find_element(By.NAME,"my-colors")
colorpicker.send_keys("#000000")
print("color changed")
time.sleep(1)
datepicker=driver.find_element(By.NAME,"my-date")
datepicker.send_keys("10/06/2025")
print("date changed")
time.sleep(1)


# selecting range error


rangeselector=driver.find_element(By.NAME,"my-range")
rangeselector.send_keys("9")
print("range changed")
# submitbtn=driver.find_element(By.CSS_SELECTOR,"button[type='submit']")
# # submitbtn.click()
time.sleep(10)